import type { Metadata } from "next";
import { FolderKanban } from "lucide-react";

import { db } from "@/lib/db";
import { can } from "@/lib/permissions";
import { getCurrentUser, getPrimaryWorkspace } from "@/lib/workspace";
import { formatDateTime } from "@/lib/format";
import { EmptyState } from "@/components/dashboard/empty-state";
import {
  DeleteAssetButton,
  DownloadLink,
  GenerateExportButton,
} from "@/components/dashboard/files-controls";

export const metadata: Metadata = {
  title: "Files",
  robots: { index: false, follow: false },
};

export const dynamic = "force-dynamic";

const KIND_LABELS: Record<string, string> = {
  EXPORT: "Export",
  RUN_EVIDENCE: "Run evidence",
  AVATAR: "Avatar",
  DOCUMENT: "Document",
};

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export default async function FilesPage() {
  const user = await getCurrentUser();
  const primary = user ? await getPrimaryWorkspace(user.id) : null;
  if (!user || !primary) return null;
  const { workspace, role } = primary;

  const assets = await db.asset.findMany({
    where: { workspaceId: workspace.id, kind: { not: "AVATAR" } },
    orderBy: { createdAt: "desc" },
    take: 100,
    include: { createdBy: { select: { name: true, email: true } } },
  });

  const canExport = can(role, "files.export");

  return (
    <div className="mx-auto max-w-5xl">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Files</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Exports and run evidence, all access-logged. Downloads are signed
            to workspace members only.
          </p>
        </div>
        {canExport && <GenerateExportButton />}
      </div>

      {assets.length === 0 ? (
        <div className="mt-8">
          <EmptyState
            icon={FolderKanban}
            title="No files yet"
            description={
              canExport
                ? "Generate your first usage export — a CSV of the runs ledger, useful for finance reconciliation and audits."
                : "Files generated by your team will appear here."
            }
          />
        </div>
      ) : (
        <ul className="mt-8 divide-y rounded-2xl border bg-card">
          {assets.map((asset) => {
            const canDelete =
              asset.createdById === user.id || can(role, "files.delete");
            return (
              <li
                key={asset.id}
                className="flex items-center gap-3 px-5 py-3.5 text-sm"
              >
                <div className="min-w-0 flex-1">
                  <p className="truncate font-medium">{asset.name}</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    {KIND_LABELS[asset.kind] ?? asset.kind} ·{" "}
                    {formatBytes(asset.sizeBytes)} ·{" "}
                    {asset.createdBy?.name ?? asset.createdBy?.email ?? "system"}{" "}
                    · {formatDateTime(asset.createdAt)}
                  </p>
                </div>
                <DownloadLink assetId={asset.id} name={asset.name} />
                <DeleteAssetButton assetId={asset.id} canDelete={canDelete} />
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
