/** M8 production proof: pending → approved → expired/suspended → reactivated → deleted. */
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
const BASE=process.env.BASE_URL!; const URL=process.env.DATABASE_URL!; let bad=0;
const ok=(v:boolean,n:string)=>{console.log(`${v?"✓":"✗"} ${n}`);if(!v)bad++};
function cookie(r:Response){const h=r.headers as unknown as {getSetCookie?:()=>string[]};return (h.getSetCookie?.()??[r.headers.get("set-cookie")??""]).map(x=>x.split(";")[0]).join("; ")}
async function login(email:string,password:string){const c=await fetch(BASE+"/api/auth/csrf");const {csrfToken}=await c.json() as {csrfToken:string};const r=await fetch(BASE+"/api/auth/callback/credentials",{method:"POST",redirect:"manual",headers:{"content-type":"application/x-www-form-urlencoded",Cookie:cookie(c)},body:new URLSearchParams({csrfToken,email,password})});return cookie(r)}
async function main(){if(!BASE||!URL)throw Error("BASE_URL and DATABASE_URL required");const db=new PrismaClient({datasources:{db:{url:URL}}});let id="";let ws="";try{const stamp=Date.now().toString(36);const target=await db.user.create({data:{name:"M8 Pending",email:`m8+${stamp}@moniclaw.invalid`,passwordHash:await bcrypt.hash("m8-password-91!",12),memberships:{create:{role:"OWNER",workspace:{create:{name:"M8",slug:"m8-"+stamp}}}}},include:{memberships:true}});id=target.id;ws=target.memberships[0].workspaceId;ok(target.accessStatus==="PENDING","open registration default is PENDING");const pendingCookie=await login(target.email,"m8-password-91!");const pending=await fetch(BASE+"/dashboard",{headers:{Cookie:pendingCookie}});ok((await pending.text()).includes("Awaiting activation"),"pending user receives honest full-screen state");const pendingApi=await fetch(BASE+"/api/agents",{headers:{Cookie:pendingCookie}});const pendingApiBody=await pendingApi.json() as {error?:string};ok(pendingApi.status===403&&pendingApiBody.error==="access_suspended","pending API receives 403 access_suspended");
const owner=await db.user.findFirst({where:{email:"demo@moniclaw.dev",deletedAt:null}});if(!owner)throw Error("demo owner missing");const ownerCookie=await login(owner.email,"password123");const patch=async(operation:string,accessUntil?:string|null)=>fetch(BASE+`/api/admin/users/${id}`,{method:"PATCH",headers:{"content-type":"application/json",Cookie:ownerCookie},body:JSON.stringify({operation,accessUntil,accessNote:"M8 e2e bank transfer"})});let r=await patch("approve",null);ok(r.status===200,"owner approves pending account");ok((await db.user.findUnique({where:{id}}))?.accessStatus==="ACTIVE","approval persists ACTIVE");const active=await fetch(BASE+"/dashboard",{headers:{Cookie:pendingCookie}});ok(!(await active.text()).includes("Awaiting activation"),"approved user has full dashboard access");r=await patch("extend","2020-01-01");ok(r.status===200,"owner sets expiry");const expired=await fetch(BASE+"/dashboard",{headers:{Cookie:pendingCookie}});ok((await expired.text()).includes("Access expired"),"expired account is blocked honestly");r=await patch("suspend");ok(r.status===200,"owner suspends account");r=await patch("reactivate",null);ok(r.status===200,"owner reactivates account");r=await fetch(BASE+`/api/admin/users/${id}`,{method:"DELETE",headers:{Cookie:ownerCookie}});ok(r.status===200,"owner deletion succeeds and frees seat");ok(!!(await db.user.findUnique({where:{id}}))?.deletedAt,"deleted account is soft-deleted");}finally{if(ws)await db.workspace.delete({where:{id:ws}}).catch(()=>{});if(id)await db.user.delete({where:{id}}).catch(()=>{});await db.$disconnect()}process.exit(bad?1:0)}main();
